clean up mass build sites logging

diff --git a/content_sync/pipelines/definitions/concourse/mass-build-sites.yml b/content_sync/pipelines/definitions/concourse/mass-build-sites.yml
--- a/content_sync/pipelines/definitions/concourse/mass-build-sites.yml
+++ b/content_sync/pipelines/definitions/concourse/mass-build-sites.yml
@@ -100,8 +100,9 @@ jobs:
       run:
         path: bash
         args:
-          - -exc
+          - -ec
           - |
+            ANY_FAILED=0
             CURDIR=$(pwd)
             if [[ "$GIT_KEY" != "" ]]
             then
@@ -123,40 +124,70 @@ jobs:
               S3_PATH=$(echo $1 | jq -c '.s3_path' | tr -d '"')
               SITE_URL=$(echo $1 | jq -c '.site_url' | tr -d '"')
               BASE_URL=$(echo $1 | jq -c '.base_url' | tr -d '"')
+              echo "STARTING PUBLISH OF $NAME" > /dev/tty
               if [[ "$SITE_URL" == null || "$S3_PATH" == null ]]
               then
                 return 1
               fi
               if [[ "$GITKEYSSH" != "" ]]
               then
-                git -c core.sshCommand="ssh $GITKEYSSH -o StrictHostKeyChecking=no" clone -b ((ocw-site-repo-branch)) ((markdown-uri))/$SHORT_ID.git || return 1
+                git -c core.sshCommand="ssh $GITKEYSSH -o StrictHostKeyChecking=no" clone -b ((ocw-site-repo-branch)) ((markdown-uri))/$SHORT_ID.git --quiet || return 1
               else
-                git clone -b ((ocw-site-repo-branch)) ((markdown-uri))/$SHORT_ID.git || return 1
+                git clone -b ((ocw-site-repo-branch)) ((markdown-uri))/$SHORT_ID.git --quiet || return 1
               fi
               cd $CURDIR/$SHORT_ID
               cp ../webpack-json/webpack.json ../ocw-hugo-themes/base-theme/data
-              hugo --config ../ocw-hugo-projects/$STARTER_SLUG/config.yaml --baseUrl /$PREFIX/$BASE_URL --themesDir ../ocw-hugo-themes/ ((build-drafts))  || return 1
+              echo "RUNNING HUGO BUILD FOR $NAME" > /dev/tty
+              HUGO_RESULT=$(hugo --config ../ocw-hugo-projects/$STARTER_SLUG/config.yaml --baseUrl /$PREFIX/$BASE_URL --themesDir ../ocw-hugo-themes/ ((build-drafts)) --quiet) || HUGO_RESULT=1
+              if [[ $HUGO_RESULT == 1 ]]
+              then
+                echo "HUGO BUILD FAILED FOR $NAME" > /dev/tty
+                return 1
+              fi
               cd $CURDIR
-              aws s3((cli-endpoint-url)) sync s3://((ocw-studio-bucket))/$S3_PATH s3://((ocw-bucket))/$PREFIX/$SITE_URL --metadata site-id=$NAME || return 1            
-              aws s3((cli-endpoint-url)) sync $SHORT_ID/public s3://((ocw-bucket))/$PREFIX/$BASE_URL --metadata site-id=$NAME || return 1
-              curl -X POST -H 'Content-Type: application/json' --data '{"webhook_key":"((open-webhook-key))","prefix":"'"$SITE_URL"/'","version":"((version))"}' ((open-discussions-url))/api/v0/ocw_next_webhook/
-              curl -X POST -H 'Content-Type: application/json' -H 'Authorization: Bearer ((api-token))' --data '{"version":"((version))","status":"succeeded"}' ((ocw-studio-url))/api/websites/$NAME/pipeline_status/
+              echo "STARTING S3 SYNC FOR $NAME" > /dev/tty
+              STUDIO_S3_RESULT=$(aws s3((cli-endpoint-url)) sync s3://((ocw-studio-bucket))/$S3_PATH s3://((ocw-bucket))/$PREFIX/$SITE_URL --metadata site-id=$NAME --only-show-errors) || STUDIO_S3_RESULT=1
+              if [[ $STUDIO_S3_RESULT == 1 ]]
+              then
+                echo "SYNCING s3://((ocw-studio-bucket))/$S3_PATH to s3://((ocw-bucket))/$PREFIX/$SITE_URL FAILED FOR $NAME" > /dev/tty
+                return 1
+              fi
+              PUBLISH_S3_RESULT=$(aws s3((cli-endpoint-url)) sync $SHORT_ID/public s3://((ocw-bucket))/$PREFIX/$BASE_URL --metadata site-id=$NAME --only-show-errors) || PUBLISH_S3_RESULT=1
+              if [[ $PUBLISH_S3_RESULT == 1 ]]
+              then
+                echo "SYNCING $SHORT_ID/public to s3://((ocw-bucket))/$PREFIX/$SITE_URL failed for $NAME" > /dev/tty
+                return 1
+              fi
+              # START NON-DEV
+              curl -s -X POST -H 'Content-Type: application/json' --data '{"webhook_key":"((open-webhook-key))","prefix":"'"$SITE_URL"/'","version":"((version))"}' ((open-discussions-url))/api/v0/ocw_next_webhook/
+              # END NON-DEV
+              curl -s -X POST -H 'Content-Type: application/json' -H 'Authorization: Bearer ((api-token))' --data '{"version":"((version))","status":"succeeded"}' ((ocw-studio-url))/api/websites/$NAME/pipeline_status/
               rm -rf $SHORT_ID
+              echo "PUBLISH OF $NAME COMPLETE" > /dev/tty
               return 0
             }
             fail_site()
             {
               NAME=$(echo $1 | jq -c '.name' | tr -d '"')
-              curl -X POST -H 'Content-Type: application/json' -H 'Authorization: Bearer ((api-token))' --data '{"version":"((version))","status":"errored"}' ((ocw-studio-url))/api/websites/$NAME/pipeline_status/
+              echo "PUBLISH OF $NAME FAILED" > /dev/tty
+              curl -s -X POST -H 'Content-Type: application/json' -H 'Authorization: Bearer ((api-token))' --data '{"version":"((version))","status":"errored"}' ((ocw-studio-url))/api/websites/$NAME/pipeline_status/
             }
-            jq -c '.sites[]' publishable_sites/sites.json | while read i; do
-              result=$(process_site $i) || result=1
-              echo "RESULT IS $result"
-              if [[ $result == 1 ]]
+            while read SITE; do
+              RESULT=$(process_site $SITE) || RESULT=1
+              if [[ $RESULT == 1 ]]
               then
-                fail_site $i
+                ANY_FAILED=1
+                fail_site $SITE
               fi
-            done
+            done <<< $(jq -c '.sites[]' publishable_sites/sites.json)
+            if [[ $ANY_FAILED == 1 ]]
+            then
+              echo "FAILED BUILDS HAPPENED" > /dev/tty
+              exit 1
+            else
+              echo "ALL BUILDS SUCCEEDED" > /dev/tty
+              exit 0
+            fi
   # START NON-DEV
   - task: clear-cdn-cache
     timeout: 1m
